### ISSUE TITLE
How to get asset version in template?

### ISSUE THREAD

**Issue by david-xie** [miracle2k/flask-assets#100]
To take advantage of CDN, I decide to upload compiled static files to CDN and use them in template. However, I don't know how to get version of assets in template.

Currently I only know one variable that I can use, which is `ASSET_URL`, but it doesn't help. Is it possible to just get version like `ASSET_VERSION`, or get fullname of asset, like `ASSET_FILENAME`?

What's more, besides `ASSET_URL`, what else variables can we use?

**Comment by miracle2k** [comment]
`ASSET_URL`` will automatically include the version. The version is read from a manifest. See here:

http://webassets.readthedocs.org/en/latest/expiring.html#about-manifests

**Comment by david-xie** [comment]
@miracle2k how to make it return CDN url?

On Monday, 18 April 2016, Michael Elsdörfer <notifications@github.com>
wrote:

> ASSET_URL` will automatically include the version. The version is read
> from a manifest. See here:
>
> http://webassets.readthedocs.org/en/latest/expiring.html#about-manifests
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/miracle2k/flask-assets/issues/100#issuecomment-211435956>
>


-- 
----
Best Regards,
David Xie
Founder of ScriptFan technology community - http://scriptfan.com
Manager of Xi'an GDG (Google Developer Group)
http://about.me/davidx

-----------------
Everything happens for a reason. Attitude determines everything!

**Comment by miracle2k** [comment]
With ``app.config['assets_url']`` you can generate a different prefix. But this is problematic with blueprint. In general, Flask itself doesn't have a good CDN story. But you might want to look at an extension like flask-cdn.

**Comment by david-xie** [comment]
I will try it out, thank you

On Monday, 18 April 2016, Michael Elsdörfer <notifications@github.com>
wrote:

> With app.config['assets_url'] you can generate a different prefix. But
> this is problematic with blueprint. In general, Flask itself doesn't have a
> good CDN story. But you might want to look at an extension like flask-cdn.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/miracle2k/flask-assets/issues/100#issuecomment-211440339>
>


-- 
----
Best Regards,
David Xie
Founder of ScriptFan technology community - http://scriptfan.com
Manager of Xi'an GDG (Google Developer Group)
http://about.me/davidx

-----------------
Everything happens for a reason. Attitude determines everything!
