### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by citizen-stig** [miracle2k/flask-assets#101]
Please release new version of the package, because https://github.com/miracle2k/flask-assets/issues/73 has been fixed in december and I would like to apply this fix without installing a package from git

**Comment by dappiu** [comment]
You can always fork, put a tag on a commit that works for you and do `pip install git+git://github.com/my_username/flask-assets.git@my_tag` (works in requirements.txt too), or refer a commit/branch/tag from the master branch of the original repository, using the same format.

**Comment by jirikuncar** [comment]
@dappiu forking and tagging a commit works if you are building an app. I'm working on framework for digital repositories where we would like people to run just `pip install` for installing everything.

Hence, I'm in favor of [Release early, release often](https://en.wikipedia.org/wiki/Release_early,_release_often) strategy to create a tight feedback loop between developers and testers or users of Flask-Assets.

**Comment by dappiu** [comment]
@jirikuncar I perfectly agree with you, I was just suggesting a temporary solution until the author takes some step here because I don't feel like we can do much more otherwise. That, and maybe leaving a **+1** on this thread's first comment, which I just did :)
