### ISSUE TITLE
new ext import format

### ISSUE THREAD

**Issue by eMerzh** [miracle2k/flask-assets#102]
With the new flask 0.11 released in seems that flask-assets raise an error

```
/path/venv/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.script is deprecated, use flask_script instead.
  .format(x=modname), ExtDeprecationWarning
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
```

it seems that it come from 

```
  File "my/app/extensions.py", line 4, in <module>
    from flask_assets import Environment
  File "/path/venv/lib/python2.7/site-packages/flask_assets.py", line 345, in <module>
    from flask.ext import script
```

**Comment by gtalarico** [comment]
I am getting the same msg with 0.11.
I disabled flask-assets and the warning went away.
Could it be a dependency? pip list below.

![image](https://cloud.githubusercontent.com/assets/9513968/17312483/10bdfc7e-5821-11e6-8fe7-f0ab530c2978.png)

**Comment by andyhd** [comment]
@gtalarico are you importing from `flask.ext.script` in your `run.py`? It should be `flask_script` if you're using Flask 0.11
