### ISSUE TITLE
cant add glyphicons bootstrap

### ISSUE THREAD

**Issue by euri10** [miracle2k/flask-assets#104]
maybe it's a bad usage from my side, but I cant get the glyphicons from bootstrap to be rendered, when I use the bower structure

The error i got is 
"NetworkError: 404 NOT FOUND - http://localhost:5000/static/fonts/glyphicons-halflings-regular.woff2"

I "imported" bootstrap through bower so I have this structure
```
.
├── auth
├── bower_components
│   ├── bootstrap
│   ├── bootstrap-datepicker
│   ├── d3
│   ├── jquery
│   ├── leaflet
│   ├── leaflet-routing-machine
│   └── leaflet-sidebar
├── bower.json
├── decorators.py
├── __init__.py
├── main
├── models.py
├── static
│   ├── css 
│   ├── flags
│   └── webassets-external
├── tasks.py
├── templates
│   ├── base.html 
├── translations
├── utils.py

```

I import the assets in my __init__.py:

```
def create_assets(app):
    assets = Environment(app)
    assets.load_path = [os.path.join(os.path.dirname(__file__), 'bower_components'),
                        os.path.join(os.path.dirname(__file__), 'static')]
    js = Bundle(
        # jquery
        Bundle('jquery/dist/jquery.js'),
        # bootstrap
        Bundle('bootstrap/dist/js/bootstrap.js'),
        # bootstrap-datepicker
        Bundle('bootstrap-datepicker/dist/js/bootstrap-datepicker.js'),
        # d3
        Bundle('d3/d3.min.js'),
        Bundle('leaflet/dist/leaflet.js'),
        Bundle('leaflet-routing-machine/dist/leaflet-routing-machine.js'),
        filters='jsmin',
        output='js_all.js')
    css = Bundle(
        Bundle('css/custom.css'),
        # bootstrap
        Bundle('bootstrap/dist/css/bootstrap.css'),
        # bootstrap-datepicker
        Bundle('bootstrap-datepicker/dist/css/bootstrap-datepicker.css'),
        Bundle('leaflet/dist/leaflet.css'),
        Bundle('leaflet-routing-machine/dist/leaflet-routing-machine.css'),
        filters='cssmin',
        output='css_all.css')

    assets.register('js_all', js)
    assets.register('css_all', css)

    return assets


def create_app(config_name):
#.......more code
    assets = create_assets(app)

    return app
```

and use them in my template base.html with 
```
        {% assets "css_all" %}
            <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}">
        {% endassets %}
        {% assets "js_all" %}
            <script type="text/javascript" src="{{ ASSET_URL }}"></script>
        {% endassets %}
```

so I understand Bundles urls are relative to the directory of the environment, so I could copy past the fonts folders in bootstrap/dist to my static directory and I'd be good, but isn't there a way that picks automatically the fonts folder ?

**Comment by miracle2k** [comment]
``flask-assets`` will not copy the font files (or image files) to the the static directory, unfortunately. 

The only way this will work is if the files that the browser needs are actually served at some URL. Right now, your Flask app simply does not serve these files. Using ``load_path``, flask-assets can find them when it wants to apply filters, merge them together etc. It will write the output file to ``static``, where flask will serve it. 

But any file the browser needs, you'll need to tell Flask to serve it. 

In Flask, that usually means putting it into the ``./static`` directory.
