### ISSUE TITLE
Flask.ext.script > flask_script deprecation warning

### ISSUE THREAD

**Issue by gtalarico** [miracle2k/flask-assets#112]
ExtDeprecationWarning: Importing flask.ext.script is deprecated, use flask_script instead.
  .format(x=modname), ExtDeprecationWarning

I keept getting this warning, turns out it was from flask-assets.

I  changed line 345 from:
from flask.ext import scripts 
to
from flask_scripts import script

**Comment by arnuschky** [comment]
This doesn't work, the line has to be changed to:
```
    from flask_script import Command
```

**Comment by miracle2k** [comment]
I think this should be fixed with the latest release.
