### ISSUE TITLE
Flask-assets 0.12 still depends on webassets-0.11.1

### ISSUE THREAD

**Issue by akkumar** [miracle2k/flask-assets#113]
Is that intended ? 

Does this need a patch to upgrade Flask-Assets from 0.12 to webassets-0.12  ? 

Or, can we expect a different release of Flask-Assets, in sync with webassets-0.12 ?

**Comment by miracle2k** [comment]
That was intended. It should still be compatible with 0.11, so I decided to leave that as a spec. Not sure if that was the right decision.
