### ISSUE TITLE
Issue with jinja 2.9

### ISSUE THREAD

**Issue by mohamed-aziz** [miracle2k/flask-assets#120]
There seems to be an issue while using flask-assets with jinja 2.9 and 2.9.1 in the template there isn't the asset_url, also [this test](https://github.com/miracle2k/flask-assets/blob/master/tests/test_env.py) fails.

I wonder if someone could investigate this issue further more?

**Comment by miracle2k** [comment]
Fixed by https://github.com/miracle2k/webassets/issues/477.
