### ISSUE TITLE
Upgrading to Jinja2 version 2.9 breaks "{{ ASSET_URL }}"

### ISSUE THREAD

**Issue by smewp** [miracle2k/flask-assets#122]
Upgrading from Jinja2 version 2.8.1 to version >= 2.9 seems to break {{ ASSET_URL }} imports for common.css and common.js and now need to be explicit with the paths.

For example, this used to work:

    {% assets "css_all" %}
    <link type="text/css" href="{{ ASSET_URL }}" rel="stylesheet">
    {% endassets %}
    {% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script> 
    {% endassets %}

Now need explicit paths:

    {% assets "css_all" %}
    <link rel="stylesheet" href="{{ url_for('static', filename='pub/css/common.css') }}">
    {% endassets %}
    {% assets "js_all" %}
    <script type="text/javascript" src="{{ url_for('static', filename='pub/js/common.js') }}"></script>
    {% endassets %}

**Comment by cjmielke** [comment]
Happening on our end too. Rolling back to 2.8 gave us a quick fix for now
pip install jinja2==2.8

**Comment by miracle2k** [comment]
This is related to https://github.com/miracle2k/webassets/issues/477. You need to upgrade webassets to fix it.
