### ISSUE TITLE
Flask-Assets doesn't watch @import'd SASS files

### ISSUE THREAD

**Issue by acnebs** [miracle2k/flask-assets#133]
Flask-Assets is not aware of any files that are not directly listed in a `Bundle`.

So, if I had a `boxes.scss`, which looked like this:

```
@import 'colors';

...
```

And I changed anything in the `colors.scss` file, these changes would not be seen by Flask-Assets and `boxes.scss` would not be recompiled. Is there any way to do this without manually having to add every SASS file to a Flask-Assets `Bundle`? I want to use the features that SASS provides, as the workflow is much faster when imports are handled by SASS.

By way of example, [wellington](https://github.com/wellington/wellington) does this. If you tell wellington to watch a single SASS file with SASS imports, it will recompile if one of the imported files changes.

**Comment by miracle2k** [comment]
The solution for this is the ``depends`` option on the bundle, which lets you glob the files that should be considered when deciding on recompilation (short docs here: https://webassets.readthedocs.io/en/latest/bundles.html)
