### ISSUE TITLE
Update for newer webassets version? Cleancss is broken in old version (since cleancss@4)

### ISSUE THREAD

**Issue by idchlife** [miracle2k/flask-assets#138]

**Comment by Markus00000** [comment]
webassets 2.0 [has been released](https://pypi.org/project/webassets/#history) with [support for clean-css 4](https://github.com/miracle2k/webassets/commit/9eba59055927abf3eb0b0b0748ce23a36cc78986).

**Comment by miracle2k** [comment]
A new version of flask-assets will come as well.
