### ISSUE TITLE
flask-assets breaks in flask-3.0

### ISSUE THREAD

**Issue by MarcoEvasi** [miracle2k/flask-assets#159]
Since _request_ctx_stack is been removed from Flask 3.0.x, then Flask-Assets breaks.

**Comment by greyli** [comment]
Fixed in #155

**Comment by sarthikg** [comment]
@greyli, was this fix released? It seems like the last version release (2.0) is still from December 2019.

**Comment by greyli** [comment]
[2.1.0](https://github.com/miracle2k/flask-assets/releases/tag/2.1.0) released. Please try it out!
