### ISSUE TITLE
Extra args not being parsed from Flask's app.config when using flask-assets init_app

### ISSUE THREAD

**Issue by raja** [miracle2k/flask-assets#34]
I am setting config variables for Flask-Asset's in the documentation, for example

```
# Flask-Assets / webassets
ASSETS_DEBUG = True
ASSETS_UGLIFYJS_EXTRA_ARGS = ['-nc']
```

I am initializing the assets environment in an application factory:

```
assets = Environment()

def create_app(config=None):
    app = Flask(__name__)
    if config is not None:
        app.config.from_object(config)
    db.init_app(app)
    assets.init_app(app)
```

While the DEBUG option works fine.. the extra args for uglifyjs do not get passed. Perhaps I am doing something wrong? Are all Flask config options prepended with ASSETS_ parsed?

Thanks again for webassets + Flask-Assets. Truly invaluable.

**Comment by ebrensi** [comment]
hello!  Another question about filter options.  I am trying to apply Google's Closure compiler filter, which works fine with the default whitespace-only option.   However, I want to use the ADVANCED_OPTIMIZATIONS setting.
https://developers.google.com/closure/compiler/docs/compilation_levels?csw=1

I tried including in my `config.py`
```
CLOSURE_COMPRESSOR_OPTIMIZATION = "ADVANCED_OPTIMIZATIONS"
```
but that is not happening.  Am I missing something?  Should this be an environment variable instead?
Thanks btw!  I love flask-assets.
