### ISSUE TITLE
Config error with pyScss

### ISSUE THREAD

**Issue by stevenleeg** [miracle2k/flask-assets#70]
Hey everyone,

I'm having an issue trying to use `pyScss` instead of the external `sass` filter. When I switch over to `pyScss` I get the following error:

```
File "/path/to/project/.env/lib/python2.7/site-packages/webassets/filter/pyscss.py", line 97, in setup
    scss.config.STATIC_ROOT = self.static_root or self.env.directory
AttributeError: 'module' object has no attribute 'config'
```

Here's the code I'm using to set up the environment:

``` python
app = Flask(__name__)
app.config["ASSETS_DEBUG"] = True

assets = Environment(app)
assets.url = app.static_url_path

scss = Bundle("stylesheets/main.scss", 
        filters="pyscss", 
        output="all.css", 
        depends="stylesheets/partials/*.scss")

assets.register("style", scss)
```

Nothing too complicated/fancy and it worked a-okay when `pyscss` was replaced with `sass`. I'm a bit confused as to what could be going wrong here. Any thoughts?

Thanks in advance!

**Comment by pdxbmw** [comment]
Ah, thank you! Looks like I was doing the same. I appreciate you posting your resolution

**Comment by stevenleeg** [comment]
Glad it helped!
