### ISSUE TITLE
Can you release a new version?

### ISSUE THREAD

**Issue by heynemann** [miracle2k/flask-assets#81]
I would love to use flask-assets CDN integration, but the current release (0.10) does not have it.

Thanks for a great library.

**Comment by density** [comment]
Yes, would be great to have a release with the CDN features. @miracle2k,  what issues can we help you tackle so we can get a new version out quickly?

**Comment by markashleybell** [comment]
+1: I just spent quite a bit of time trying to get flask-cdn to work with flask-assets using [these docs](http://flask-assets.readthedocs.org/en/latest/) before realising the pip version was not up to date... if there's anything we can do to help please let us know!

**Comment by danielsilva** [comment]
+1: I just spent quite a bit of time trying to get flask-cdn to work with flask-assets using [these docs](http://flask-assets.readthedocs.org/en/latest/) before realising the pip version was not up to date... if there's anything we can do to help please let us know!

Even asked a [question on SO](http://stackoverflow.com/questions/29563170/flask-cdn-does-not-create-correct-url-on-template/29578013) regarding this.

**Comment by abathur** [comment]
:+1: just lost time to this as well.

**Comment by gprasanth** [comment]
+1

**Comment by jlev** [comment]
:100: just lost time to this as well. Including the requirement directly from GitHub isn't a terrible solution, but it would be great if the version on PyPI was up to date with the docs.
