### ISSUE TITLE
Flask-Assets or Bundles are not resovling the correct URL when multiple Blueprints are used

### ISSUE THREAD

**Issue by jgill333** [miracle2k/flask-assets#96]
Having an issue that I think may be better served here vs. where I originally posted the question about Flask-Assets not working with multiple Flask Blueprints. The setup and configuration for the assets and blueprints are here if anyone could point me in the right direction or note that this is indeed a known issue with Flask-Assets: http://stackoverflow.com/questions/33528956/flask-assets-or-bundles-are-not-resovling-the-correct-url-when-multiple-blueprin

I'm having an issue that I really hope someone can keep me from banging my head against the table about.

* I have a Flask app with multiple Blueprints that each have their own static and templates directories.
When only one Blueprint is registered and utilized the assets URL for bundled CSS and Javascript are both correctly resolved
* However, when two or more Blueprints are resolved only the URLs for the assets in the last registered Blueprint resolve correctly (everything else seems to think that it's assets should be served out of the root static directory)
* I'm getting incorrect asset URLs when templates from the Blueprints resolve the asset URLs. The URLs resolved are built incorrectly as if they should be served from a root static directory (which I would still like the overall app to have a static directory so that 400 and 500 errors can render pages using that).

The issue is that when multiple blueprints are used (each with their own bundles.py type file that builds bundles) you get links like the following in all but the last registered blueprint: 
`http://{host}/static/public_css_app (404)`

When it should be:
`http://{host}/{blueprint_name}/static/public_css_app (200)`

**Comment by miracle2k** [comment]
When flask-assets generates a link to a source file, it takes the blueprint prefix into account. If a source file is in the static folder of blueprint A, then 'a/foo.css' should generate the right link.

The *output* files of a blueprint, by default, are written to the app static directory, and urls to the output files should be generated using that url. 

A different behaviour would be a bug. Check the FlaskResolver class to see how and why urls might be generated the wrong way in your case.

**Comment by jgill333** [comment]
Thanks for the reply! I will step through what that class using the specific config that I have.

**Comment by jgill333** [comment]
Found the issue and it's not a bug in Flask-Assets, but it is user error and potentially a useful thing for other people to know. I was resetting the Environment with each Blueprint load, by not realizing the scope/global nature of it when registering bundles. So it came down to the scoping of that and the order of operations in the code.

    # Setup global "bundled_assets" variable before importing and registering Blueprints
    # if each Blueprint registers its bundles
    bundled_assets = Environment(application)
